# Input Columns
TICKET_SUMMARY: "Ticket Summary"
INTERACTION_CONTENT: "Interaction content"

# Type Columns to test
TYPE_COLS:
 - "y2"
 - "y3"
 - "y4"

CLASS_COL: 
- ["Others", "Problem/Fault", "Suggestion",""]
- ["AppGallery-Install/Upgrade", "AppGallery-Use", "Coupon/Gifts/Points Issues", "Third Party APPs", "VIP / Offers / Promotions", "General", "Others", ""]
- ["AppGallery not loading", "Can't download Apps", "Can't install Apps", "Can't update Apps", "Can't use or acquire", "Cannot connect - Server", "Cooperated campaign issue", "Offers / Vouchers / Promotions", "Other download/install/update issue", "Others", "Personal data", "Refund", "Security issue / malware", "UI Abnormal in Huawei AppGallery", ""]

GROUPED: "y1"
