# Input Columns
TICKET_SUMMARY: 'Ticket Summary'
INTERACTION_CONTENT: 'Interaction content'

# Type Columns to test
TYPE_COLS:
 - 'y2'
 - 'y3'
 - 'y4'

CLASS_COL: 'y2'
GROUPED: 'y1'

# New columns for Intent, Tone, and Resolution
INTENT_COL: 'y2'
TONE_COL: 'y3'
RESOLUTION_COL: 'y4'
